# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
  App\Security\AuthenticationSuccessHandler:
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_authentication_success,
          method: onAuthenticationSuccess,
        }
  App\EventListener\ScheduleListener:
    tags:
      - { name: doctrine.event_subscriber }

  App\Controller\PostImageGameController:
    tags: ["controller.service_arguments"]

  App\Controller\PostImageRankController:
    tags: ["controller.service_arguments"]

  App\Controller\PostImageUserController:
    tags: ["controller.service_arguments"]

  App\Controller\PostImageTeamController:
    tags: ["controller.service_arguments"]

  App\Controller\GetManagerTeamController:
    tags: ["controller.service_arguments"]

  App\Controller\AddPlayerTeamController:
    tags: ["controller.service_arguments"]

  App\Controller\GetPlayerScheduleController:
    tags: ["controller.service_arguments"]

  App\Controller\ApproveTeamController:
    tags: ["controller.service_arguments"]

  App\Controller\GetPlayersListController:
    tags: ["controller.service_arguments"]

  App\Controller\PostUserController:
    tags: ["controller.service_arguments"]

  App\Controller\ValidationEmailController:
    tags: ["controller.service_arguments"]

  App\EventSubscriber\JwtValidationSubscriber:
    tags:
      - { name: kernel.event_subscriber }

  App\Controller\AddBookingController:
    tags: ["controller.service_arguments"]

  App\Controller\GetClientController:
    tags: ["controller.service_arguments"]

  App\Controller\GetPlayerController:
    tags: ["controller.service_arguments"]

  App\Controller\CancelBookingController:
    tags: ["controller.service_arguments"]

  App\Controller\GetAllStatsController:
    tags: ["controller.service_arguments"]

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
