api_platform:
  title: Hello API Platform
  version: 1.0.0
  show_webby: false

  formats:
    json:
      mime_types: ["application/json"]
    jsonld:
      mime_types: ["application/ld+json"]
    html:
      mime_types: ["text/html"]

  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
    extra_properties:
      standard_put: true

    # Move the serializer configuration here
    serializer:
      default_context:
        groups: ["read", "create", "update"]

  swagger:
    api_keys:
      JWT:x:
        name: Authorization
        type: header

  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
