vich_uploader:
  db_driver: orm
  mappings:
    rank_image:
      uri_prefix: /images/rank
      upload_destination: "%kernel.project_dir%/public/images/rank"
      namer: Vich\UploaderBundle\Naming\OrignameNamer

    game_image:
      uri_prefix: /images/games
      upload_destination: "%kernel.project_dir%/public/images/games"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
