vich_uploader:
  db_driver: orm
  mappings:
    rank_image:
      uri_prefix: /images/ranks
      upload_destination: "%kernel.project_dir%/public/images/ranks"
      namer: Vich\UploaderBundle\Naming\OrignameNamer

    game_image:
      uri_prefix: /images/games
      upload_destination: "%kernel.project_dir%/public/images/games"
      namer: Vich\UploaderBundle\Naming\OrignameNamer

    user_image:
      uri_prefix: /images/users
      upload_destination: "%kernel.project_dir%/public/images/users"
      namer: Vich\UploaderBundle\Naming\OrignameNamer

    team_image:
      uri_prefix: /images/teams
      upload_destination: "%kernel.project_dir%/public/images/teams"
      namer: Vich\UploaderBundle\Naming\OrignameNamer
