on:
  push:
    branches:
      - main
      - develop
      - feature/unitTest
      - feature/ci
  pull_request:
    branches:
      - main
      - develop
      - feature/unitTest

jobs:
  test:
    name: Run PHPUnit tests in Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Restore composer cache
      - name: Restore Composer cache
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Restore Docker image cache
      - name: Restore Docker image cache
        uses: actions/cache@v2
        with:
          path: /tmp/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Install dependencies
      - name: Install dependencies
        run: composer install

      # Build Docker image
      - name: Build Docker image
        run: docker build .

      # Install Docker compose
      - name: Install Docker compose
        run: sudo apt-get install docker-compose

      # Run Docker container
      - name: Docker compose up
        run: docker-compose up -d

      # Run PHPUnit tests (Make sh to connect to the Docker container) then run the tests
      - name: Run PHPUnit tests
        run: |
          make sh
          composer update
          composer install 
          ./vendor/bin/phpunit
          exit
