name: Symfony Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4-alpine
        env:
          POSTGRES_DB: symfony_test
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo_pgsql, intl

      - name: Install Composer dependencies
        run: composer install --no-dev --no-interaction

      - name: Prepare database
        run: php bin/console doctrine:database:create --env=test
        env:
          DATABASE_URL: postgresql://root:root@localhost:5432/symfony_test

      - name: Run tests
        run: php bin/phpunit
